### ISSUE TITLE
Support for Data Streams

### ISSUE THREAD

**Issue by Caoimhin89** [yandex-cloud/go-sdk#10]
Is there currently any work underway to add Yandex Data Streams to the SDK? - https://cloud.yandex.ru/services/data-streams

**Comment by MAnyKey** [comment]
Yandex Data Streams has an HTTP API compatible with AWS Kinesis Data Streams, so you can use aws-sdk-go with Yandex Data Streams. Unfortunately, we currently only have usage [examples for Python](https://cloud.yandex.com/en/docs/data-streams/operations/aws-sdk/create), but the same parameters apply to aws-sdk-go as well.

Currently, there are no plans, that I am aware of, of providing a gRPC API of our own and hence add it to the go-sdk.

You can add a feature request [here](https://cloud.yandex.ru/features) (sorry, the webpage is in Russian only).
