### ISSUE TITLE
Добавление сервисов AI: SpeechKit Translate Vision

### ISSUE THREAD

**Issue by Shagrat2** [yandex-cloud/go-sdk#2]
Добавьте пожалуйста AI: SpeechKit Translate Vision

**Comment by Shagrat2** [comment]
Translate Pull Request
https://github.com/yandex-cloud/go-sdk/pull/4

**Comment by Shagrat2** [comment]
Добавлен Pul Request https://github.com/yandex-cloud/go-sdk/pull/5

**Comment by Shagrat2** [comment]
Похоже их никто не читает

**Comment by MAnyKey** [comment]
Сервисы были добавлены ещё 27 января в https://github.com/yandex-cloud/go-sdk/commit/d3fce5fb4fc0f2e88dad0a9da91881bc58c99212
Прошу прощения, что не отписался ранее.
